#+TITLE: tex4ht regression tests

A unit consists of three main files:

- ~foo.tex~

 Minimal (non-)working example (MWE) ~.tex~ file.
 Would be nice to have metadata:
           - author/date of a file
           - issue description
           - solution description
           - bug ID (?)
           - etc.

- ~foo.s~

  Pre-saved results file, which is compared against build results.
  Can be in various formats: ~html~, ~xml~, ~css~, plain text, ~svg~, binary (~png~)

- ~foo.Makefile~

  Define rules:
  1. how to produce results
  2. how to compare results

* Setting new unit test

0. save your MWE ~.tex~ file as ~FOO.tex~

1. create ~FOO.Makefile~ from ~t.Makefile~ template
   and ~FOO.s~ -- empty

#+BEGIN_SRC 
make FOO.new
#+END_SRC
or
#+BEGIN_SRC
make file=FOO new
#+END_SRC


Amend ~FOO.Makefile~. Requires ~GNU M4 macro~ processor.

* Checking 

#+BEGIN_SRC 
make FOO.check
#+END_SRC

or

#+BEGIN_SRC
make file=FOO check
#+END_SRC

This stage copies ~FOO.*~ files to ./build folder, runs ~make -f FOO.Makefile~,
which produces ~FOO.diff~ file. Empty ~diff~ file is /SUCCESS/, non-empty -- /FAILURE/

Checking the bundle:

#+BEGIN_SRC
make checkall
#+END_SRC

* Saving

#+BEGIN_SRC 
make FOO.save
#+END_SRC

or

#+BEGIN_SRC
make file=FOO save
#+END_SRC


Saves the output produced in the _check_ stage as ~FOO.s~

* t.Makefile template file
  
This file is a template for ~FOO.Makefile~ generation.

Variables: ~FILE~

Needs GNU M4 macro processor.


* External dependencies

  - GNU make (version 4.1)
  - GNU M4 macro processor (version 1.4). for Makefile templates
  - pandoc (version 1.12). For standalone html file generation. see ,e.g., t-suits

